name: Release plugin on semver version tag
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # You might need to adjust this value to your own version
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with: 
          draft: true
          generate_release_notes: true
